debug: false
server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: attendance-service
  config:
    import: optional:file:../infra/env/.env[.properties]
  jackson:
    property-naming-strategy: SNAKE_CASE
  # ===================================================
  # Kafka メッセージング設定 (Producer)
  # ===================================================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:shared-kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false # 受信側で余計なクラス型ミスマッチを起こさない安全設定
  # ===================================================
  # データソース & HikariCP設定
  # ===================================================
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # プール内の最大コネクション数
      maximum-pool-size: 10
      # 常に保持しておく最低限の待機コネクション数
      minimum-idle: 2
      # コネクション取得のタイムアウト時間（ミリ秒：デフォルト30秒）
      connection-timeout: 30000
      # コネクションの最大生存時間（ミリ秒：デフォルト30分）※DB側の切断設定より短くするのが鉄則！
      max-lifetime: 1800000
  # ===================================================
  # インフラツール設定 (Flyway / jOOQ)
  # ===================================================
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: true
  jooq:
    sql-dialect: postgres
# ===================================================
# 外部API連携設定 (Hrmos / LINE WORKS)
# ===================================================
app:
  hrmos:
    api:
      company-url: ${HRMOS_COMPANY_URL} # 環境変数から取得
      secret-key: ${HRMOS_SECRET_KEY}   # 環境変数から取得
      base-url: ${HRMOS_BASE_URL:}api/${app.hrmos.api.company-url}${HRMOS_API_VERSION:/v1}
  kafka:
    topics:
      notification: ${APP_KAFKA_TOPIC_NOTIFICATION:notification-topic}
      unstamped-alert: ${APP_KAFKA_TOPIC_UNSTAMPED_ALERT:unstamped-alert-topic}
      unstamped-direct: ${APP_KAFKA_TOPIC_UNSTAMPED_DIRECT:unstamped-direct-topic}
      attendance-irregularity: ${APP_KAFKA_TOPIC_ATTENDANCE_IRREGULARITY:attendance-irregularity-topic}
  batch:
    alert-cron1: ${ALERT_CRON1:}
    alert-cron2: ${ALERT_CRON2:}
    sync-master-cron: ${SYNC_MASTER_CRON:}

# ===================================================
# API仕様書
# ===================================================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.computer_rescuer.attendance_management: ${LOG_LEVEL_APP_ROOT:INFO}
